[project]
name = "AISLOP"
version = "0.1.0"
description = "Artifical Intelligence Stitches Lazy Outsourced Prototypes"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.29.5",
    "openai>=1.91.0",
    "python-dotenv>=1.1.0",
]
